{"username":"fredx","text":"hi everybody!","roomname":"lobby"},
{"username":"Ephraim","text":"hello","roomname":"lobby"},
{"username":"Ephraim","text":"hello","roomname":"lobby"},
{"username":"Ephraim","text":"what up bro","roomname":"lobby"},
{"username":"Ephraim","text":"hi everybody","roomname":"lobby"},
{"username":"Ephraim","text":"hello","roomname":"lobby"},
{"username":"Ephraim","text":"hello","roomname":"lobby"},
{"username":"Ephraim","text":"hello","roomname":"lobby"},
{"username":"Ephraim","text":"Ephraim is here!","roomname":"lobby"},
{"username":"Ephraim","text":"hello","roomname":"lobby"},
{"username":"Ephraim","text":"blah blah blah","roomname":"lobby"},
{"username":"Ephraim","text":"who's here?","roomname":"Berkeley"},
{"username":"Ephraim","text":"anyone?","roomname":"Berkeley"},
{"username":"Ephraim","text":"sup?","roomname":"Berkeley"},
{"username":"Ephraim","text":"snegwegwe","roomname":"Berkeley"},
{"username":"Ephraim","text":"xcxcxcccxcx","roomname":"Berkeley"},
{"username":"Ephraim","text":"sdfsdfsdf","roomname":"lobby"},
{"username":"Ephraim","text":"dfsdfwe","roomname":"Berkeley"},
{"username":"Ephraim","text":"wrwer","roomname":"lobby"},
{"username":"Ephraim","text":"hi","roomname":"lobby"},
{"username":"Ephraim","text":"hi","roomname":"Berkeley"},
{"username":"Ephraim","text":"message","roomname":"Berkeley"}